
version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,apigateway,dynamodb,cloudformation,iam,sts,logs,ssm,s3
      - DEBUG=1
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
